
language: php

php: '7.2'

install:
  - npm install

script:
  - npm run lint
  - npm run lint-release

deploy:
  # To production.
  - provider: script
    script:
      - npm run deploy-production
    skip_cleanup: true
    on:
      branch: master
  # To staging.
  - provider: script
    script:
      - npm run deploy-staging
    skip_cleanup: true
    on:
      branch: develop

branches:
  only:
  - master
  - develop

cache:
  npm: true
  directories:
    - $HOME/.composer/cache

notifications:
  email: false
